### ISSUE TITLE
Export Issues (OSX)

### ISSUE THREAD

**Issue by hasahmed** [salomonelli/best-resume-ever#109]
### Case
- Bug

## Issue
Running the export command results in pdfs with no data, just template styling. 
No errors are reported. Here is on of the exported PDFs [material-dark.pdf](https://github.com/salomonelli/best-resume-ever/files/1404673/material-dark.pdf)

## Info
- Operating System: OSX Sierra 10.12.6
- Node-Version: 8.7.0

## Reproduce

run `npm run export` from top of repo directory

**Comment by salomonelli** [comment]
I can not reproduce this error. Maybe somebody with OSX can?

**Comment by HallPatrickS** [comment]
I am having the same error. Also have the same OSX and Node-Version.

**Comment by salomonelli** [comment]
PR #113 is merged and should have solved the issue.
