### ISSUE TITLE
Sidebar templates GitHub links flow outside div

### ISSUE THREAD

**Issue by nickatnight** [salomonelli/best-resume-ever#118]
### Case
- BUG

## Issue
For a Github user whose name is greater than 9 characters, the username will flow into adjacent div.

## Info
- Operating System: OSX
- Node-Version: v8.8.0

## Reproduce
Change the Github info in `resume/data.yml` to a name that is greater than 9 chars.

<img width="463" alt="overflow" src="https://user-images.githubusercontent.com/8783431/31985329-8e3656ec-b919-11e7-93da-6d47cca093c3.png">

**Comment by pubkey** [comment]
Yes. The resumes break if you add too much data here and there. Then you have to adjust the styling.
This cannot be solved globally because next to every website or template will break when it's content overflows at a certain degree.
