### ISSUE TITLE
npm run export |  Unhandled 'error' event

### ISSUE THREAD

**Issue by codesdk** [salomonelli/best-resume-ever#13]
==> npm run export

> best-resume-ever@1.0.0 export /Users/coder/repos/salomonelli/best-resume-ever
> concurrently "npm run dev" "npm run pdf" --success first --kill-others --raw

> best-resume-ever@1.0.0 dev /Users/coder/repos/salomonelli/best-resume-ever
> node build/dev-server.js

> best-resume-ever@1.0.0 pdf /Users/coder/repos/salomonelli/best-resume-ever
> node node/app.js

> Starting dev server...
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1033:11)
    at exports._exceptionWithHostPort (util.js:1056:20)
    at Server._listen2 (net.js:1276:14)
    at listen (net.js:1312:10)
    at Server.listen (net.js:1403:7)
    at Function.listen (/Users/coder/repos/salomonelli/best-resume-ever/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/Users/coder/repos/salomonelli/best-resume-ever/build/dev-server.js:89:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3

npm ERR! Darwin 16.6.0
npm ERR! argv "/Users/coder/.nvm/versions/node/v7.7.2/bin/node" "/Users/coder/.nvm/versions/node/v7.7.2/bin/npm" "run" "dev"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! best-resume-ever@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the best-resume-ever@1.0.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the best-resume-ever package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs best-resume-ever
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls best-resume-ever
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/coder/repos/salomonelli/best-resume-ever/npm-debug.log

npm ERR! Darwin 16.6.0
npm ERR! argv "/Users/coder/.nvm/versions/node/v7.7.2/bin/node" "/Users/coder/.nvm/versions/node/v7.7.2/bin/npm" "run" "export"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! best-resume-ever@1.0.0 export: `concurrently "npm run dev" "npm run pdf" --success first --kill-others --raw`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the best-resume-ever@1.0.0 export script 'concurrently "npm run dev" "npm run pdf" --success first --kill-others --raw'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the best-resume-ever package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently "npm run dev" "npm run pdf" --success first --kill-others --raw
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs best-resume-ever
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls best-resume-ever
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/coder/repos/salomonelli/best-resume-ever/npm-debug.log

**Comment by salomonelli** [comment]
Hello @codesk 

this means that the port 8080 is being used by another application. You need to stop `npm run dev` first, then you can run `npm run export`.
