### ISSUE TITLE
Change Education translation in pt-br

### ISSUE THREAD

**Issue by GabrielCoelho** [salomonelli/best-resume-ever#132]
### Case
- ENHANCEMENT

## Issue
The right term that we (Brazilians) use in a CV is **Formação Acadêmica**, translating to English is same to say "Educational Background". To make this repository more profissional for the Brazilians I suggest this improvement on [src/lang/pt-br.js][link1] file, changing `Educação` to `Formação Acadêmica` as it is written. 
If you need some proof, I have a link of one article written october of this year using the same term. You can [access here][link2]

## Info
- Operating System: Linux (Ubuntu 16.04.3)
- Node-Version: 8.9.0

[link1]: https://github.com/salomonelli/best-resume-ever/blob/master/src/lang/pt-br.js
[link2]: https://pleno.news/brasil/confira-5-dicas-para-que-seu-curriculo-chame-a-atencao.html

**Comment by CorentinDy** [comment]
You can pull request by following the readme file in the project `PULL_REQUEST_TEMPLATE.md`

 REMOVE EVERYTHING WRITTEN IN UPPERCASE

## This PR contains:
 - IMPROVED DOCS
 - A TYPO-FIX
 - A BUGFIX
 - A NEW FEATURE
 - A BREAKING CHANGE
 - SOMETHING ELSE


## Describe the problem you have without this PR
DESCRIBE PROBLEM HERE OR LINK TO AN ISSUE



IMPORTANT: READ THIS BEFORE SUBMISSION:

- IF YOUR PULL-REQUEST CONTAINS A NEW FEATURE, IT MUST HAVE BEEN DISCUSSED AT AN ISSUE BEFORE
- DO NOT ADD GENERATED FILES TO THE PULL-REQUEST (NOTHING FROM THE pdf-FOLDER)

**Comment by pubkey** [comment]
PR is merged. Thx @GabrielCoelho 
Closing this issue.
