### ISSUE TITLE
Export do not work

### ISSUE THREAD

**Issue by radap** [salomonelli/best-resume-ever#136]
### Case
- HELP QUESTION

## Issue
Run Dev opens empty white PDFs in the browser, and export finishing successfully but in the PDF folder I have only the templates.
What is wrong?

## Info
- Operating System: WINDOWS 10
- Node-Version: 8.9

**Comment by BohdanOrlov** [comment]
Same for MacOS.

```
DONE  Compiled successfully in 6882ms                                                                                                                  12:52:05

> Listening at http://localhost:8080

Connected to server ...
Exporting ...
Finished exports.
```

But no files at /pdf

**Comment by youngjuning** [comment]
![2017-11-18_152023](https://user-images.githubusercontent.com/13204332/32978148-2f704eee-cc77-11e7-8fda-83298b1c2f52.png)

**Comment by pubkey** [comment]
@radap  please run `npm run dev` and open `localhost:8080` to ensure everything works.
@youngjuning  You screenshot does not make sense here.
