### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by CorentinDy** [salomonelli/best-resume-ever#139]
### Case
- ENHANCEMENT

## Issue
`born` ... `in` ...
not translated in other language ( at least in french )

## Info
- Operating System: W10 Pro
- Node-Version: 8.9.0

**Comment by vitalkanev** [comment]
Strange. I can't find this string.

    vitalkanev@vitalkanev-HP-Artful:~/clones/best-resume-ever$ git grep born
    vitalkanev@vitalkanev-HP-Artful:~/clones/best-resume-ever$

**Comment by CorentinDy** [comment]
![image](https://user-images.githubusercontent.com/6079068/32489557-b158dc52-c3b0-11e7-86e1-786f12d81dd9.png)

**Comment by mbndr** [comment]
I remember this as I wrote the language feature. This is only used in `material-dark` theme and I wasn't sure if I should add this. You can add this in the language files in a PR, but meanwhile there are so many languages I think it would be good to write a function which merges a complete language (`en`) with the configured (e.g. `fr`) to make all new terms at least in English available. After that people from the different countries can send PRs to make their language file complete.
(Not sure if I wrote that understandable)

**Comment by CorentinDy** [comment]
yes it might be a good solution, hard to think about the structure right now but can be resolved as one file function to handle all languages !
If I understood correctly what you said

**Comment by mbndr** [comment]
I think it's possible to add a merge between `en` and the user language in this file: https://github.com/salomonelli/best-resume-ever/blob/master/src/resumes/options.js

**Comment by pubkey** [comment]
The translation is now here https://github.com/salomonelli/best-resume-ever/blob/master/src/lang/en.js#L3
Currently only translated for `en` and `de`.
