### ISSUE TITLE
fs and child_process were not found

### ISSUE THREAD

**Issue by THEONE10211024** [salomonelli/best-resume-ever#151]
I imported app.js in home.vue file like the following，
**<script>
  import Vue from 'vue';
  import * as App from '../../node/app'; // **Here I add the code!**
  export default Vue.component('resume', {
    name: 'app'
  });
</script>**
and then I run the cmd: npm run dev,and  coming with the error:
**These dependencies were not found:

* fs in ./node/app.js
* child_process in ./node/app.js

To install them, you can run: npm install --save fs child_process**

Could you please help me to figure it out ?Thanks in advance!

**Comment by GabrielCoelho** [comment]
Have you already tryed to run this snippet? 
```bash
$ npm install --save fs child_process
```

**Comment by THEONE10211024** [comment]
I have run $ npm install --save fs child_process，and after that I run ：npm run dev，it still came with the same error.However,when I run the cmd:npm run export,it works fine.Did I missing some steps?

**Comment by pubkey** [comment]
Which node-version?

**Comment by THEONE10211024** [comment]
It's my mistake,I try to use it in client end,sorry!
