### ISSUE TITLE
Multiple Page Resume or resizable content

### ISSUE THREAD

**Issue by rainolf** [salomonelli/best-resume-ever#161]
### Case
bug

## Issue
Resume truncated id data.yml contains too much records

## Info
- Operating System: Linux Ubuntu
- Node-Version: 0.92

## Reproduce
Example add additional education records:

education:
- degree: Master of Arts
  timeperiod: March 2012 - December 2013
  description: Major in Hacking and Computer Penetration, University A, New York, USA.

- degree: Bachelor of Science
  timeperiod: March 2009 - December 2011
  description: Major in Engineering, University B, Los Angeles, USA.

- degree: Bachelor of Science
  timeperiod: March 2009 - December 2011
  description: Major in Engineering, University B, Los Angeles, USA.
  
- degree: Bachelor of Science
  timeperiod: March 2009 - December 2011
  description: Major in Engineering, University B, Los Angeles, USA.
  
- degree: Bachelor of Science
  timeperiod: March 2009 - December 2011
  description: Major in Engineering, University B, Los Angeles, USA.
  
- degree: Bachelor of Science
  timeperiod: March 2009 - December 2011
  description: Major in Engineering, University B, Los Angeles, USA.

**Comment by pubkey** [comment]
Yes. The resumes break if you add too much data here and there. Then you have to adjust the styling.
This cannot be solved globally because next to every website or template will break when it's content overflows at a certain degree.

**Comment by rainolf** [comment]
ok...thanks...

i will do...
