### ISSUE TITLE
Right procedure to add section

### ISSUE THREAD

**Issue by rainolf** [salomonelli/best-resume-ever#162]
### Case
help question

## Issue
Hello,
please could you explain me teh right procedure to add a section ex: Awards
-> modify template
-> add data in data.yml
-> etc.

## Info
- Operating System: Ubuntu
- Node-Version: 0.92

Thanks

**Comment by pubkey** [comment]
Hey @rainolf This repo is basically build on vuejs. I recomment to start [here](https://vuejs.org/v2/guide/). And after that you will know everything you have to know to change the resume.
