### ISSUE TITLE
Use port value from config/index.js on export

### ISSUE THREAD

**Issue by johnthad** [salomonelli/best-resume-ever#167]
## Issue
Currently `npm run export` is hard coded to use port 8080. It would be nice to use the `dev.port` value from `config/index.js` instead.

## Info
- Operating System: macOS 10.13.1 (High Sierra)
- Node-Version: v8.9.2

## Reproduce
Implement this enhancement by adding `const config = require('../config');` to `config/index.js` and changing two lines:

Change line 10 from

    const req = http.request('http://localhost:8080/#/', response => res(response.statusCode));

to

    const req = http.request(`http://localhost:${config.dev.port}/#/`, response => res(response.statusCode));

and change line 47 from

    await page.goto('http://localhost:8080/#/resume/' + dir.name, {waitUntil: 'networkidle', networkIdleTimeout: 5E3});

to

    await page.goto(`http://localhost:${config.dev.port}/#/resume/` + dir.name, {waitUntil: 'networkidle', networkIdleTimeout: 5E3});

**Comment by pubkey** [comment]
Hi @johnthad 
This is a good proposal.
Can you do a pull-request with the changes?

**Comment by johnthad** [comment]
Done. See #174
