### ISSUE TITLE
Parse Markdown in person.js

### ISSUE THREAD

**Issue by mattcheah** [salomonelli/best-resume-ever#17]
I'd like to be able to customize how I list information in the resume and the best way I can think to do this is to add markdown support. Let me know if you'd like that and I can submit a PR.

**Comment by salomonelli** [comment]
Hello @mattcheah 

I need to think about this. This had been already requested in some way. But I am not yet sure if markdown is the ideal way. Maybe somebody else has another idea of fixing this

**Comment by mattcheah** [comment]
Makes sense. Another thought I had was that a user could just pass in an array for job description bullet points, which I think would be a little easier to execute if you wanted to go with this.

**Comment by salomonelli** [comment]
Yes, maybe it would be better if you extend the job array. A PR with new templates and examples allowing the bullet points would be great! I am closing this for now.
