### ISSUE TITLE
Integration with GitHub Pages

### ISSUE THREAD

**Issue by cezar-carneiro** [salomonelli/best-resume-ever#18]
Do you think it's a good idea to enable integration with GitHub Pages? This would allow devs to deploy their resume right from the command line using [gh-pages](https://www.npmjs.com/package/gh-pages)

**Comment by nacimgoura** [comment]
from what I see there is a page but it is not finalized.

**Comment by salomonelli** [comment]
Hello, 

I think that would be a great idea. The existing gh-pages stuff is not working. I sort of forgot it ... A PR would be great :)

**Comment by agmadt** [comment]
+1
and maybe a list of 'custom templates' made by developers?

**Comment by cristijora** [comment]
Would be willing to help on this one :) 
@cezar-carneiro you thought simply supporting gh-pages as an npm script or something else?

**Comment by cezar-carneiro** [comment]
@cristijora I was thinking on npm scripts indeed... If we first create a `build` script to compile and minify a resume to a folder, we could then run a `gh-pages -d` on that folder sending the built resume to the repository/branch where it would be online.
What do you think? Feel free to make a PR and close this issue.

**Comment by salomonelli** [comment]
npm script would be great but please do not use a seperate branch, rather commit the docs to /docs.

**Comment by cristijora** [comment]
I am facing some issues with the assets (especially fonts) since they have relative paths inside the imported css and won't be referenced correctly if you have a static website.

**Comment by maxpou** [comment]
If you want, I open #18.
I already did this deployments several times in the past ([example 1](https://github.com/maxpou/sw-shop-vuejs), [example 2](https://github.com/maxpou/dictionary-game)).

**Comment by cristijora** [comment]
@maxpou Thanks a lot. Didn't know about that. Nice tip to fix another issue I had on some other project.

**Comment by disjfa** [comment]
I've done this a couple of times, in the scripts in the package.json file.

"scripts": {
    "build": "node build/build.js",
    "ghpages": "ghpages -p dist",
    "github": "npm-run-all build ghpages",
}

And that only uses the ghpages package, https://www.npmjs.com/package/ghpages and pushes the dist folder to gh-pages branch for showing.

I just stole this code from my package. https://github.com/disjfa/vue-route-timeline . I don't know if i have time to help, but you can use this.

**Comment by maxpou** [comment]
IMHO this script is not needed.
The problem with your package is every time a PR is merged or code is pushing to master, then @salomonelli need to manually run the npm commands. 
Here, the whole deployment pipeline is completely delegated by Github+Continuous Integration tool (Travis). See on my examples (comment above). I just need to merge a PR and its automatically deploy to gh-pages!!

Less human interactions = less oversights 😉

**Comment by cristijora** [comment]
@maxpou This is all good but wasn't this issue about 
>  This would allow devs to deploy their resume right from the command line using gh-pages
This is more helpful for people who forked the repo and want to quickly put their resume on github with no friction. 
Also there is a better, more popular gh-pages package https://www.npmjs.com/package/gh-pages

**Comment by maxpou** [comment]
My bad, you right: this solution is probably a better one that the CI/CD one.

**Comment by cezar-carneiro** [comment]
Guys, why don't we keep both things? Originally I was think on the `gh-pages -d` script, but I really liked the deploy with Travis.

**Comment by AYastrebov** [comment]
does it work?

**Comment by maxpou** [comment]
> does it work?

deploying on GH pages? yes.
