### ISSUE TITLE
Unable to run: "npm run dev"

### ISSUE THREAD

**Issue by Andmat7** [salomonelli/best-resume-ever#188]
### Case
- HELP QUESTION

## Issue
Unable to run: "npm run dev"
Iterm show me:
> best-resume-ever@1.0.0 predev /Users/afcorredor/Sites/best-resume-ever
> check-node-version --node ">= 8.0.0"

> best-resume-ever@1.0.0 dev /Users/afcorredor/Sites/best-resume-ever
> node build/dev-server.js

/Users/afcorredor/Sites/best-resume-ever/node_modules/webpack-dev-middleware/node_modules/mime/Mime.js:31
        throw new Error(
        ^

Error: Attempt to change mapping for "wasm" extension from "application/wasm" to "application/wasm". Pass `force=true` to allow this, otherwise remove "wasm" from the list of extensions for "application/wasm".
    at Mime.define (/Users/afcorredor/Sites/best-resume-ever/node_modules/webpack-dev-middleware/node_modules/mime/Mime.js:31:15)
    at Object.<anonymous> (/Users/afcorredor/Sites/best-resume-ever/node_modules/webpack-dev-middleware/lib/middleware.js:8:6)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/afcorredor/Sites/best-resume-ever/node_modules/webpack-dev-middleware/index.js:5:20)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)

## Info
- Operating System: OSX
- Node-Version: v9.2.1

## Log File
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@5.5.1
3 info using node@v9.2.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle best-resume-ever@1.0.0~predev: best-resume-ever@1.0.0
6 verbose lifecycle best-resume-ever@1.0.0~predev: unsafe-perm in lifecycle true
7 verbose lifecycle best-resume-ever@1.0.0~predev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/afcorredor/Sites/best-resume-ever/node_modules/.bin:/usr/local/opt/opencv3/bin:/Users/afcorredor/.yarn/bin:/usr/local/opt/php70/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/afcorredor/.fzf/bin
8 verbose lifecycle best-resume-ever@1.0.0~predev: CWD: /Users/afcorredor/Sites/best-resume-ever
9 silly lifecycle best-resume-ever@1.0.0~predev: Args: [ '-c', 'check-node-version --node ">= 8.0.0"' ]
10 silly lifecycle best-resume-ever@1.0.0~predev: Returned: code: 0  signal: null
11 info lifecycle best-resume-ever@1.0.0~dev: best-resume-ever@1.0.0
12 verbose lifecycle best-resume-ever@1.0.0~dev: unsafe-perm in lifecycle true
13 verbose lifecycle best-resume-ever@1.0.0~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/afcorredor/Sites/best-resume-ever/node_modules/.bin:/usr/local/opt/opencv3/bin:/Users/afcorredor/.yarn/bin:/usr/local/opt/php70/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/afcorredor/.fzf/bin
14 verbose lifecycle best-resume-ever@1.0.0~dev: CWD: /Users/afcorredor/Sites/best-resume-ever
15 silly lifecycle best-resume-ever@1.0.0~dev: Args: [ '-c', 'node build/dev-server.js' ]
16 silly lifecycle best-resume-ever@1.0.0~dev: Returned: code: 1  signal: null
17 info lifecycle best-resume-ever@1.0.0~dev: Failed to exec dev script
18 verbose stack Error: best-resume-ever@1.0.0 dev: `node build/dev-server.js`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
18 verbose stack     at EventEmitter.emit (events.js:159:13)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:159:13)
18 verbose stack     at maybeClose (internal/child_process.js:943:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
19 verbose pkgid best-resume-ever@1.0.0
20 verbose cwd /Users/afcorredor/Sites/best-resume-ever
21 verbose Darwin 17.3.0
22 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
23 verbose node v9.2.1
24 verbose npm  v5.5.1
25 error code ELIFECYCLE
26 error errno 1
27 error best-resume-ever@1.0.0 dev: `node build/dev-server.js`
27 error Exit status 1
28 error Failed at the best-resume-ever@1.0.0 dev script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]

**Comment by edzluhan** [comment]
I had the same issue, try updating your babel-eslint version to 8.1.0 and rxjs to 5.5.6, it worked here.

**Comment by nogenem** [comment]
@edzluhan I also had to update webpack-dev-middleware to 2.0.3 to fix the problem here...

**Comment by edzluhan** [comment]
@nogenem thanks, forgot that one

**Comment by Andmat7** [comment]
Thanks @nogenem  working fine, thanks also to @edzluhan , please do not close this until update the packaje.json.

**Comment by pubkey** [comment]
Should be solved now. I merged the PR with the updated webpack-dev-middleware and travis [works](https://travis-ci.org/salomonelli/best-resume-ever/builds/320407602?utm_source=github_status&utm_medium=notification) again
