### ISSUE TITLE
Material-vue not found

### ISSUE THREAD

**Issue by NicolasBouhours** [salomonelli/best-resume-ever#19]
Hi
I've clone and install this project
I got a error when i run mpn run dev
`
import '../resumes/material-dark.vue';
// import '../resumes/material-blue.vue';
import '../resumes/left-right.vue';
import '../resumes/oblique.vue';
import '../resumes/side-bar.vue';
`
Material-blue.vue is imported on file resumes.js

But this file is not present on the repo.

If i comment this line all is okay

If it can help you

**Comment by salomonelli** [comment]
Hello @NicolasBouhours 

sorry for that, should be fixed now.

**Comment by NicolasBouhours** [comment]
Wow very fast fix @salomonelli 
Thank's for all, it's a very nice project :)
