### ISSUE TITLE
npm run export throwing syntax error ,( windows8.1  )

### ISSUE THREAD

**Issue by pavanyogi** [salomonelli/best-resume-ever#21]
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

\resumes\best-resume-ever>npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm WARN best-resume-ever@1.0.0 No repository field.
npm WARN best-resume-ever@1.0.0 No license field.

\Downloads\resumes\best-resume-ever>npm run export

> best-resume-ever@1.0.0 export \Downloads\resumes\best-resume-ever
> concurrently "npm run dev" "npm run pdf" --success first --kill-others --raw

> best-resume-ever@1.0.0 dev \Downloads\resumes\best-resume-ever
> node build/dev-server.js

> best-resume-ever@1.0.0 pdf \Downloads\resumes\best-resume-ever
> node node/app.js

\Downloads\resumes\best-resume-ever\node\app.js:22
    .mergeMap(async() => {
                   ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "pdf"
npm ERR! node v6.9.1
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! best-resume-ever@1.0.0 pdf: `node node/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the best-resume-ever@1.0.0 pdf script 'node node/app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the best-resume-ever package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node/app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs best-resume-ever
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls best-resume-ever
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     \AppData\Roaming\npm-cache\_logs\2017-09-12T10_07_36_379Z-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "export"
npm ERR! node v6.9.1
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! best-resume-ever@1.0.0 export: `concurrently "npm run dev" "npm run pdf" --success first --kill-others --raw`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the best-resume-ever@1.0.0 export script 'concurrently "npm run dev" "npm run pdf" --success first --kill-others --raw'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the best-resume-ever package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently "npm run dev" "npm run pdf" --success first --kill-others --raw
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs best-resume-ever
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls best-resume-ever
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     \AppData\Roaming\npm-cache\_logs\2017-09-12T10_07_37_294Z-debug.log

Downloads\resumes\best-resume-ever>

**Comment by nacimgoura** [comment]
Hello,
This works if you have a version of nodeJS greater than 7.4, you are in 6.9.1 :smile:
