### ISSUE TITLE
npm run export  working but no resume generated in pdf folder

### ISSUE THREAD

**Issue by pavanyogi** [salomonelli/best-resume-ever#24]
DONE  Compiled successfully in 9128ms

> Listening at http://localhost:8080

Connected to server ...
Exporting ...
Finished exports.

Downloads\resumes\best-resume-ever>

**Comment by czonios** [comment]
Hey @pavanyogi 
I can try to help but the info is too little to help me come to any conclusions as to why it doesn't work for you.
First things first, the resumes **should** be exported at `best-resume-ever/pdf`.
That folder already contains the sample pdf files, and they are replaced when you run `npm run export`. 

#### Personalizing your resume:
   * edit the file `best-resume-ever/src/person.js` and
   * change the picture `best-resume-ever/src/assets/person.jpg` 

### Please note that your picture has to be named `person.jpg` and indeed be in JPEG format.

Can you check that your resumes are actually rendering by running `npm run dev` and viewing them from your browser?

**Comment by pavanyogi** [comment]
changes are reflecting , output is coming  correctly in browser , but pdf is not generating in pdf folder. I am trying to take pdf using ctrl + p  but 2 pages are generating instead of 1 page , content also spreading
![capture](https://user-images.githubusercontent.com/13834016/30338846-9e892a72-980a-11e7-953d-066b97ccfaaa.PNG)
 in two pages

**Comment by pubkey** [comment]
@pavanyogi If you print with Ctrl+P you have white borders which change the presentation-size of the content. This makes the content-div to big to fit into one page. 

Use the printing via `npm run export` which exists exactly to circumvent this type of issues.

**Comment by pavanyogi** [comment]
npm run export , does not generating pdf
![capture](https://user-images.githubusercontent.com/13834016/30342361-4e3e5094-9817-11e7-8b5c-b9f0a9d5117e.PNG)

**Comment by pubkey** [comment]
Seems like a bug.
Is this on windows?
Which node-version do you have?

**Comment by pavanyogi** [comment]
windows 8.1, node 8.4.0

**Comment by pubkey** [comment]
Could not reproduce :(
Any windows-user here which can tell if the export works?

**Comment by czonios** [comment]
I don't see why Windows would be a problem since this is in a node environment, however bugs like that are pretty common. You might want to try node 6, which appears first when you go to the nodejs download page. If that doesn't work, the bug is in Windows.

**Comment by pavanyogi** [comment]
Same problem with node version 6.9 also

**Comment by muhtarudinsiregar** [comment]
i think, because your directory have space `C:\User\Pavan Yogi\Downloads\resumes\best-resume-ever` in `Pavan Yogi`. maybe you can try in another directory without space name.

**Comment by pavanyogi** [comment]
installed in another directory without space name , now working fine , generating pdf correctly

**Comment by Wintershadow1** [comment]
It worked but now it says

npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! best-resume-ever@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the best-resume-ever@1.0.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the best-resume-ever package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs best-resume-ever
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls best-resume-ever
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dell/best-resume-ever/npm-debug.log
root@dell-Vostro-1520:/home/dell/best-resume-ever#

**Comment by Wintershadow1** [comment]
Linux 19.2
Node-Version 8.10
