### ISSUE TITLE
Customize it for other languages

### ISSUE THREAD

**Issue by zaras86** [salomonelli/best-resume-ever#274]
Hello,

how can I customize it for other language?
For example change the point "experience" to the german word "Erfahrungen" etc.

Thx

**Comment by mbndr** [comment]
You can change the language code here:
https://github.com/salomonelli/best-resume-ever/blob/master/resume/data.yml#L69

If you want "Erfahrungen" instead of "Berufserfahrung" you could change it locally in this file:
https://github.com/salomonelli/best-resume-ever/blob/master/src/lang/de.js
