### ISSUE TITLE
Error when running npm run dev

### ISSUE THREAD

**Issue by anoobbava** [salomonelli/best-resume-ever#292]
### Case

- BUG

## Issue
Error when running npm run dev

## Info
- Operating System: ubuntu 16.04 64 bit
- Node-Version: v8.0.0

## Reproduce
1. clone the repo
2. cd to path
3. run npm install 
4. run npm run dev
5. added nvm to change the version (used v8.5.0, v8.0.0,)
6. I have the node installed, then also this issue persists

npm run dev

> best-resume-ever@1.0.0 predev /home/anoobbava/ror/best-resume-ever
> check-node-version --node ">= 8.0.0"

/home/anoobbava/ror/best-resume-ever/node_modules/semver/semver.js:305
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 0.22
    at new SemVer (/home/anoobbava/ror/best-resume-ever/node_modules/semver/semver.js:305:11)
    at SemVer (/home/anoobbava/ror/best-resume-ever/node_modules/semver/semver.js:298:12)
    at /home/anoobbava/ror/best-resume-ever/node_modules/check-node-version/index.js:112:33
    at module.exports (/home/anoobbava/ror/best-resume-ever/node_modules/map-values/index.js:9:18)
    at /home/anoobbava/ror/best-resume-ever/node_modules/check-node-version/index.js:106:22
    at end (/home/anoobbava/ror/best-resume-ever/node_modules/run-parallel/index.js:16:15)
    at done (/home/anoobbava/ror/best-resume-ever/node_modules/run-parallel/index.js:20:10)
    at each (/home/anoobbava/ror/best-resume-ever/node_modules/run-parallel/index.js:26:7)
    at /home/anoobbava/ror/best-resume-ever/node_modules/run-parallel/index.js:36:43
    at /home/anoobbava/ror/best-resume-ever/node_modules/check-node-version/index.js:53:14
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! best-resume-ever@1.0.0 predev: `check-node-version --node ">= 8.0.0"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the best-resume-ever@1.0.0 predev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/anoobbava/.npm/_logs/2018-03-26T11_04_23_586Z-debug.log

**Comment by GabrielCoelho** [comment]
Check my #187 comment. I'm using Ubuntu 16.04 too.

**Comment by anoobbava** [comment]
@GabrielCoelho  how to remove this predev ?, Please update, i have limited knowledge with node

**Comment by GabrielCoelho** [comment]
I have to apologize myself in advance because my English it isn't that good. Hope you'll understand all that I'll say. 
* * *

in [package.json](https://github.com/salomonelli/best-resume-ever/blob/master/package.json) you have the `scripts`section. There you'll find the `"predev": "check-node-version --node \">= 8.0.0\"",` -> line 15. All that i've done was erase this line and try to run again. 

So, my package.json file it's now:
```js
"scripts": {
    "docs": "node build/build.js",
    "docs:serve": "cd docs/ && ws --port 8080 --rewrite '/best-resume-ever/* -> /$1'",
    "dev": "node build/dev-server.js",
    "start": "node build/dev-server.js",
    "pdf": "node scripts/export.js",
    "preview": "node scripts/preview.js",
    .
    .
    .
```

* * *

**Comment by pubkey** [comment]
The predev-script checks if you node-version if compatible with this project. If it's not, you should update node to the version mentioned in the readme which is 8.0.0 oe higher.

It looks like this scriot is broken so removing the predev is a temporary fix
