### ISSUE TITLE
Exported pdf doesn't reflect styling changes for the material-dark theme

### ISSUE THREAD

**Issue by zac11** [salomonelli/best-resume-ever#293]
## Issue
I made a couple of changes in the styling for the `material-dark` theme for my resume.  The changes reflect well on the on `localhost` when I run `npm run dev`.

However, when the run `npm run export` the exported excel doesn't reflect the changes in styling due to which the resume right column comes truncated.

## Info
- Operating System: OS-X High Sierra
- Node-Version: 9.11

## Reproduce

- Make changes to https://github.com/salomonelli/best-resume-ever/blob/master/src/resumes/material-dark.vue

Changed the `.rightCol {}` styling to have

```
.rightCol {
...
..
.block {
    width:90%;
    position:relative;
    background-color:#ffffff;
    **padding:30px;
    margin-top:15px;
    margin-bottom:15px;**
    display:inline-block;
    box-shadow:0 2px 5px 0 rgba(0,0,0,0.16), 0 2px 10px 0 rgba(0,0,0,0.12);
    .headline {
      font-weight:300;
      display:block;
      font-size:15px;
      color:rgba(0,0,0,0.870588);
    }
```

- Save Changes.

- Run `npm run dev` to see the changes in `localhost`.

- Run `npm run export` to export the pdf file.

**Comment by swatijadhav** [comment]
Verified this issue and it seems to be working fine. @pubkey We can close this issue as this no longer exists.
Thanks

**Comment by pubkey** [comment]
@swatijadhav thanks for reviewing this.
@zac11 I closed this, please reopen or comment if you think this is not resolved.
