### ISSUE TITLE
where is /resumes/material-blue.vue??

### ISSUE THREAD

**Issue by boblinux** [salomonelli/best-resume-ever#31]
### Case
bug when compiling

## Issue
where is material-blue.vue file on project?  

## Info
-WINDOWS 10
- npm version : 3.10.10
- Node-Version : v6.11.3  

## Reproduce
```
npm install
npm run dev
> node build/dev-server.js                                                
> Starting dev server...                                                                                        
ERROR  Failed to compile with 1 error                                    
 This relative module was not found:                                       
* ../resumes/material-blue.vue in ./s> 
Listening at http://localhost:8080
``` 
if i'm looking to this file in src/resumes/ folder, i don't find it, 
so with 
`import '../resumes/material-blue.vue';`
in src/resumes/resumes.js file, i get this error when compiling, but when i comment this line, it is ok, so where is hidden this file??

**Comment by pubkey** [comment]
material-blue is currently removed because of license-problems. [See](https://themeforest.net/item/material-cvresume/12374628)

It will be completely remaked and than added again. I'm sorry for that.

**Comment by boblinux** [comment]
thanks, it's ok, gl 👍
