### ISSUE TITLE
Why there is no "hobbies" section in the exported PDF

### ISSUE THREAD

**Issue by Aracki** [salomonelli/best-resume-ever#312]
## Issue

When I export themes there are no hobbies section. Even if I use default `data.yml`.

## Info
- Operating System: OSX
- Node-Version: v10.11.0

**Comment by mbndr** [comment]
Which template are you using? I think the hobbies section is only implemented in the "creative" template (https://github.com/salomonelli/best-resume-ever/blob/master/src/resumes/creative.vue#L80).

If you want this in other templates you may have to configure it yourself.

**Comment by Aracki** [comment]
Thanks. Maybe I will come back with PR. Working on custom `cool` template.
