### ISSUE TITLE
Add linkedin link to profile

### ISSUE THREAD

**Issue by IlyaOsotov** [salomonelli/best-resume-ever#316]
### Case
- FEATURE REQUEST

## Issue
It's would be great if it's will be possible to add linkedin link, I think.

## Info
- Operating System: Ubuntu 18.04
- Node-Version: 8.5.0

## Reproduce
Clone repository
Run npm install

**Comment by swatijadhav** [comment]
This feature will be available once PR https://github.com/salomonelli/best-resume-ever/pull/321 is accepted and merged.

Also, it would become easier to add any new contact links.

cc: @pubkey @salomonelli 

Thanks
