### ISSUE TITLE
Language support / customizable headings

### ISSUE THREAD

**Issue by mbndr** [salomonelli/best-resume-ever#32]
### Case
- FEATURE REQUEST

## Issue
I just created my CV with your software and I pretty like it. But I had to edit the headings like "EDUCATION" in the Vue template specific for my country.
Is there a chance to see a feature with that you can edit these headings just like the data in the `person.js` file and access them in the template like `lang.headings.education` or even to support different bulit-in languages?

## Info
- Operating System: LINUX
- Node-Version: 8.5.0

**Comment by salomonelli** [comment]
This is a good idea. A PR is welcome!

**Comment by mbndr** [comment]
I'm no JS / Node master and don't have much time at the moment but when I find time I'll take a look at the code and maybe I can help you.

**Comment by mbndr** [comment]
Would you prefer a separate file f.e. called `src/terms.js` or a full language support?
I think it would be great to first implement such a file and in a separate step add language support?
I also would prefer one single configuration file (json?) with all the configuration in it (person, language code). But that are only first thoughts looking through the code :)

**Comment by mbndr** [comment]
https://github.com/mbndr/best-resume-ever/commit/e515b0227409200409f19a7a73631005e17fa3ab
Here you can see the changes for a simple working prototype.
I think it would be great to manage everything in one configuration file, because (if I've done it correct) everytime a feature is added, all templates must import another file (or other changes must be done).

**Comment by salomonelli** [comment]
That seems fine to me. Maybe it might be be a bit more practical to have terms.js like this: 
```
import en from './en';
const terms = {
  en
};
export default terms;
```

and adjust person.js to have a "lang" property that is by default "en". 
Then templates could use 

```
<h1>{{ terms[person.lang].headings.experience }}</h1>
```

So if we need add languages, we do not need to retouch all templates again.

**Comment by mbndr** [comment]
I like that idea, I could implement this until tomorrow I think,
