### ISSUE TITLE
 Run npm install ,  failed

### ISSUE THREAD

**Issue by SeriStyle** [salomonelli/best-resume-ever#328]
### Case
-BUG

## Issue
when run npm install , Error launchingin staller，how to solve ?
  
npm ERR! path D:\my-vue\resume\best-resume-ever\node_modules\.staging\typescript-6e2eb2a5\lib\tsc.js
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'D:\my-vue\resume\best-resume-ever\node_modules\.staging\typescript-6e2eb2a5\lib\tsc.js'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'D:\my-vue\resume\best-resume-ever\node_modules\.staging\typescript-6e2eb2a5\lib\tsc.js'
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'D:\my-vue\resume\best-resume-ever\node_modules\.staging\typescript-6e2eb2a5\lib\tsc.js'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path: 'D:\\my-vue\\resume\\best-resume-ever\\node_modules\\.staging\\typescript-6e2eb2a5\\lib\\tsc.js' },
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'D:\\my-vue\\resume\\best-resume-ever\\node_modules\\.staging\\typescript-6e2eb2a5\\lib\\tsc.js\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'D:\\my-vue\\resume\\best-resume-ever\\node_modules\\.staging\\typescript-6e2eb2a5\\lib\\tsc.js',
npm ERR!   parent: 'best-resume-ever' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

## Info
- Operating System: WINDOWS 10
- Node-Version: v8.11.3

## Reproduce
 Run npm install

**Comment by SailHe** [comment]
this is not a BUG, I have a similar error before, but I may not be able to give too much help recently. Please refer to the following article.
Sort by priority: 
1. https://github.com/phoenixframework/phoenix/issues/2464
2. https://blogs.msdn.microsoft.com/matt-harrington/2012/02/23/how-to-fix-node-js-npm-permission-problems/
3. https://github.com/npm/npm/issues/18380
4. https://github.com/gee1k/notes/issues/23
