### ISSUE TITLE
White lists when removed birth section

### ISSUE THREAD

**Issue by IlyaOsotov** [salomonelli/best-resume-ever#338]
### Case
- BUG

## Issue
When I removed the birth section from my data.yml, cool and material-dark pdf returns empty white list.

## Info
- Operating System: LINUX
- Node-Version: 10.6.0

## Reproduce
Remove the birth section from your data.yml and try to open cool or material-dark pdf. It returns a white list like this:
![image](https://user-images.githubusercontent.com/17280582/56646207-cb5d0580-6687-11e9-89a9-39c99b43017c.png)

**Comment by salomonelli** [comment]
Closing this issue as the pull request has been merged.  Thanks a lot!
