### ISSUE TITLE
Documentation  Issues

### ISSUE THREAD

**Issue by saylimulay88** [salomonelli/best-resume-ever#342]
I would like to suggest enhancements to the existing documentation.

**Comment by carmelag** [comment]
Hi! Some days ago I opened a PR to help with the docs enhancement. 
Feel free to have a look: https://github.com/salomonelli/best-resume-ever/pull/357

By the way, I have a question. The check for The Travis CI build is still pending after a few days, anyone does know why?
Thank!

**Comment by salomonelli** [comment]
Please feel free to comment concrete suggestions or create a pull request. #357 has been merged. CI is passing currently.
