### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by aseem1234** [salomonelli/best-resume-ever#35]
### Case
- BUG

## Issue

When I try to run the install, I get some error messages toward the end. I am running this on a Windows 10 64-bit machine using the latest version of Node (8.5.0) and NPM (5.4.1). Not sure how to go about fixing it.  I have attached a screenshot of the errors. 

![npm error](https://user-images.githubusercontent.com/4081835/30407482-7457966e-98c6-11e7-88ed-43428194be32.png)

## Info
- Operating System: Windows 10 64-bit
- Node-Version: 8.5.0

**Comment by pavanyogi** [comment]
delete electron folder inside node_modules and run npm install command again as a root/administrator.  I also got same error . with retrying npm install , it installed successfully .
