### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added.

### ISSUE THREAD

**Issue by jodobear** [salomonelli/best-resume-ever#362]
[best-resume-ever-MaxListenersExceededWarning.log](https://github.com/salomonelli/best-resume-ever/files/4194838/best-resume-ever-MaxListenersExceededWarning.log)
### Case
- BUG

## Issue
It was perfect. I created a bunch of resumes and then suddenly i get the following error:

```
Connected to server ...
Exporting ...
Finished exports.
(node:26366) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
(node:26366) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
(node:26366) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added. Use emitter.setMaxListeners() to increase limit
(node:26366) MaxListenersExceededWarning: 
[best-resume-ever-MaxListenersExceededWarning.log](https://github.com/salomonelli/best-resume-ever/files/4194834/best-resume-ever-MaxListenersExceededWarning.log)
Possible EventEmitter memory leak detected. 11 SIGHUP listeners added. Use emitter.setMaxListeners() to increase limit
```

## Info
- Operating System: LINUX Mint 19
- Node-Version: v12.14.1

## Reproduce
Just run: `npm run export`

Maybe because `MaxListeners` are set to `10` by default, if you run `npm run export` the 11th time you get the error as can be evident from the error?

I've added the entire log output.

**Comment by jodobear** [comment]
What is this thing?!?!?! How do I get around it? I've re-cloned the repo - new clean `npm install` and it still won't go!!!!

It's messing with my head now!

WHAT the hell is this thing???? 

And i've searched and searched but, there's just no way to kill the open listeners through `node`. How the hell am i supposed to figure out where to debug this thing - i even tried it - found `addListener` in `best-resume-ever/docs/static/js/vendor.544f8f74b2921dd55bba.js` and tried:

`process.setMAxListeners(20)` but, that didn't do anything. And there is `removeAllListeners` after `addListener` in the same file.

So, how the hell do i get out of here???????

**Comment by salomonelli** [comment]
This is open source, please fix bugs. PRs are welcomed.
