### ISSUE TITLE
npm install pops an error

### ISSUE THREAD

**Issue by felexkemboi** [salomonelli/best-resume-ever#363]
`
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.12
npm WARN optional Skipping failed optional dependency /cpx/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.12
npm ERR! Linux 5.3.0-45-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
`

that error pops when I run `npm install`

**Comment by edlopen** [comment]
Hello felexkemboi,
I had the same issue. To solve it I installed Chromium. In Ubuntu 18.04.4 LTS is "sudo apt install chromium-browser".
