### ISSUE TITLE
iPad version

### ISSUE THREAD

**Issue by cnstntn-kndrtv** [salomonelli/best-resume-ever#37]
Nice work, bro. You have some bugs on mobile version. Take a look on screenshot from iPad mini. 
[https://www.dropbox.com/s/9fhz0t9mw9vr1ob/%D0%A4%D0%B0%D0%B9%D0%BB%2014.09.17%2C%208%2038%2053.png?dl=0](url)

**Comment by pubkey** [comment]
Link is broken.

**Comment by pubkey** [comment]
Please reopen without ignoring the issues-template.

**Comment by cnstntn-kndrtv** [comment]
https://www.dropbox.com/s/9fhz0t9mw9vr1ob/__killmelater.png?dl=0

**Comment by mbndr** [comment]
Not only on iPad, I saw this yesterday on my laptop, too.
