### ISSUE TITLE
browser back button is broken.

### ISSUE THREAD

**Issue by songjiayang** [salomonelli/best-resume-ever#39]
### Case
- BUG

## Info
-  Chorme: Version 60.0.3112.113 (Official Build) (64-bit)
- System: Mac Os

## Reproduce
1. Visit [home page](https://salomonelli.github.io/best-resume-ever/#/)
2. Choose 'material-dark' template.
3. Click browser back button, it  not back to home page.

**Comment by pubkey** [comment]
Could reproduce.

**Comment by pubkey** [comment]
Same on firefox.

**Comment by kivS** [comment]
The bug also blocks the links on the page.
The problem seems to be with the chromeShadowFixer -->  src/pages/resume.vue

**Comment by salomonelli** [comment]
This should be fixed now. @kivS thanks for the hint, I will take a closer look at the chromeShadowFixer

**Comment by songjiayang** [comment]
cool, fixed, thank guys.
