### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by mbndr** [salomonelli/best-resume-ever#41]
### Case
- BUG

## Issue
Since commit 42331d52f62bdbbcce93c16c947af044a71ce5b6 the images are not displayed in my browser. When I get a version before that commit, everything works fine.

## Info
- Operating System: LINUX
- Node-Version: 8.5.0

## Reproduce
`npm run dev`

**Comment by cristijora** [comment]
This is also applicable to fonts in my case. Both images and fonts are not loaded correctly due to that path "/static". It should be `assetsSubDirectory: 'static',` as it was before.

**Comment by mbndr** [comment]
Maybe a bit out of scope, but as mentioned in this comment https://github.com/salomonelli/best-resume-ever/pull/5#issuecomment-329302625 I want to create a dynamic home.

The only problem is that the logo (`<img src="../assets/logo.png" />`) is displayed correctly but as soon as I use `v-bind` to load the image dynamically it's not "converted" to an autogenerated(?) `/static` URL.
How is that processed and does anyone know how to fix this?

Not "converted" URL:
`<img v-bind:src="'../assets/preview/resume-'+template+'.png'" />`
