### ISSUE TITLE
Node needs updating in package.json

### ISSUE THREAD

**Issue by Hevski** [salomonelli/best-resume-ever#418]
### Case
BUG

## Issue
npm run export not working - node needs to be updated to 16.16.0 in package.json

## Info
- Operating System: MacOs Unix

## Reproduce
run npm run export, get error:

ERROR: npm is known not to run on Node.js v10.11.0
You'll need to upgrade to a newer Node.js version in order to use this
version of npm. You can find the latest version at https://nodejs.org/
ERROR: npm is known not to run on Node.js v10.11.0
You'll need to upgrade to a newer Node.js version in order to use this
version of npm. You can find the latest version at https://nodejs.org/

I can fix it by changing the node version in package.json and running npm i

**Comment by pubkey** [comment]
I removed the node dependency.
