### ISSUE TITLE
A supplement on docs about running the project on vscode

### ISSUE THREAD

**Issue by ycp8023** [salomonelli/best-resume-ever#420]
### A suggestion on docs about running the project

I try to follow the instructions to run the project on vscode but get the error:
 `(linebreak-style)  Expected linebreaks to be ‘CRLF‘ but found ‘LF‘ linebreak-style`. 
Then i find out the reason is using vscode to run this project. So i think maybe announce this situation in docs maybe helpful for windows users and people not familar with project . And the solution is very simple, only one line code can solve the problem
### Solution

edit the file `.eslintrc`  and change the attribute `linebreak-style` in `rules` as follow：
`"rules": { "linebreak-style": [0,"error", "windows"], }`
Then you can run `npm run dev` successfully.

**Comment by pubkey** [comment]
This is an open source project, please make a PR with a fix.
