### ISSUE TITLE
Master no longer work on different enviorments

### ISSUE THREAD

**Issue by AreYouLoco** [salomonelli/best-resume-ever#421]
### Case
HELP QUESTION

## Issue
I tried master and all different branches on different systems with different nodejs versions and I no longer can use your amazing script.
Around year ago I used it to generate CV and I got hired instantly. Now I want to help non-technical friend to make best-resume-ever and
I am wondering what I could do to help fix the master. Or maybe @salomonelli could point me to the working branch for modern systems.
Year ago it worked :(

## Info
- Operating System: Linux
- Node-Version: node16/node17/node18/node19

## Reproduce
[TO BE FILLED IN]

**Comment by pubkey** [comment]
This is an open source project, please make a PR with a fix.

**Comment by GabrielCoelho** [comment]
# A Tip that worked for me
I'm still learning VueJS and trying to improve my skills. Yesterday I was able to figure out (after search on the web) on how to make `npm run dev` works. 

I've done this steps: 

1. ### NPM Update
`npm update`

2.  ### NPM install webpack-merge
`npm i webpack-merge`

3.  ### Edit package json
```json
"scripts":{
...
	"dev": "NODE_OPTIONS='--openssl-legacy-provider' node build/dev-server.js"
...
}
```

After that, I was able to run the server on localhost. 

# The problem
I can load the index page with the router view, but when I enter in any of the resumes, it isn't loading, it's just a blank rectangle and any of the resume template loads.
I'll try more today and will update in any progress (or regress).

Just improving the discussion
