### ISSUE TITLE
ERROR WHEN RUNNING NPM RUN EXPORT

### ISSUE THREAD

**Issue by malakdlo** [salomonelli/best-resume-ever#46]
### Case
- Bug

## Issue
- Help exporting pdf

## Info
- Operating System: OSX
- Node-Version: 7.4.0

#### Command: npm run export

> best-resume-ever@1.0.0 pdf /Users/malaklopez/Projects/www/completed/resumes/best-resume-ever
> node node/app.js

/Users/malaklopez/Projects/www/completed/resumes/best-resume-ever/node/app.js:22
    .mergeMap(async() => {
                   ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! best-resume-ever@1.0.0 pdf: `node node/app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the best-resume-ever@1.0.0 pdf script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/malaklopez/.npm/_logs/2017-09-15T04_17_47_347Z-debug.log

#### Log
0 info it worked if it ends with ok
1 verbose cli [ '/Users/malaklopez/.nvm/versions/node/v7.4.0/bin/node',
1 verbose cli   '/Users/malaklopez/.nvm/versions/node/v7.4.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'pdf' ]
2 info using npm@5.4.2
3 info using node@v7.4.0
4 verbose run-script [ 'prepdf', 'pdf', 'postpdf' ]
5 info lifecycle best-resume-ever@1.0.0~prepdf: best-resume-ever@1.0.0
6 info lifecycle best-resume-ever@1.0.0~pdf: best-resume-ever@1.0.0
7 verbose lifecycle best-resume-ever@1.0.0~pdf: unsafe-perm in lifecycle true
8 verbose lifecycle best-resume-ever@1.0.0~pdf: PATH: /Users/malaklopez/.nvm/versions/node/v7.4.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/malaklopez/Projects/www/completed/resumes/best-resume-ever/node_modules/.bin:/Users/malaklopez/.nvm/versions/node/v7.4.0/bin:/Users/malaklopez/.rbenv/shims:/Users/malaklopez/.pyenv/plugins/pyenv-virtualenv/shims:/Users/malaklopez/.pyenv/shims:/Users/malaklopez/.pyenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle best-resume-ever@1.0.0~pdf: CWD: /Users/malaklopez/Projects/www/completed/resumes/best-resume-ever
10 silly lifecycle best-resume-ever@1.0.0~pdf: Args: [ '-c', 'node node/app.js' ]
11 silly lifecycle best-resume-ever@1.0.0~pdf: Returned: code: 1  signal: null
12 info lifecycle best-resume-ever@1.0.0~pdf: Failed to exec pdf script
13 verbose stack Error: best-resume-ever@1.0.0 pdf: `node node/app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/malaklopez/.nvm/versions/node/v7.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/malaklopez/.nvm/versions/node/v7.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:885:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid best-resume-ever@1.0.0
15 verbose cwd /Users/malaklopez/Projects/www/completed/resumes/best-resume-ever
16 verbose Darwin 16.7.0
17 verbose argv "/Users/malaklopez/.nvm/versions/node/v7.4.0/bin/node" "/Users/malaklopez/.nvm/versions/node/v7.4.0/bin/npm" "run" "pdf"
18 verbose node v7.4.0
19 verbose npm  v5.4.2
20 error code ELIFECYCLE
21 error errno 1
22 error best-resume-ever@1.0.0 pdf: `node node/app.js`
22 error Exit status 1
23 error Failed at the best-resume-ever@1.0.0 pdf script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by salomonelli** [comment]
I know the docs say a minimum of node v7.4 is required. But could you please try using the latest node version?

**Comment by malakdlo** [comment]
Thanks!!!
