### ISSUE TITLE
Github link is showed incompletely in material-blue template

### ISSUE THREAD

**Issue by sunilkumarc** [salomonelli/best-resume-ever#51]
### Case
Bug

## Issue
Github link is not showed completely in **material-blue** template when usernames are longer.

## Info
- Operating System: OSX
- Node-Version: 3.10.10

## Reproduce
Just run the application using some long username for **github** section in person.js and open material-blue template.

<img width="329" alt="screen shot 2017-09-16 at 4 36 43 pm" src="https://user-images.githubusercontent.com/3911000/30511779-ad1a90f8-9afd-11e7-9a11-e5ca26647019.png">

**Comment by pubkey** [comment]
Hi @sunilkumarc 
Yes, if your username is too long, it won't fit into the sidebar. But the same is if you have a too long email-adress or first-name. This is not something which can be fixed for every possible case globally.
As workaround I recommend to add a linebreak to your own fork of this repo.
