### ISSUE TITLE
person.about only in purple theme

### ISSUE THREAD

**Issue by mbndr** [salomonelli/best-resume-ever#58]
### Case
- DOC QUESTION

## Issue
The attribute `person.about` is currently only used in purple theme. Should this be mentioned somewhere?

**Comment by mubaidr** [comment]
I have created a pull-request with this feature: https://github.com/salomonelli/best-resume-ever/pull/92

**Comment by salomonelli** [comment]
It is ok, if some templates have some sections (e.g. projects or about me) and others not. So I am closing this. 

Thanks @mubaidr, I will take a look at the PR.
