### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by kyleweise** [salomonelli/best-resume-ever#65]
### Case
- HELP QUESTION

## Issue
Trouble installing best-resume-ever 

## Info
- Operating System: OSX 
- Node-Version:  v8.5.0 

## Reproduce
Is there a more detailed explanation on how to install? I could clone the repo perfectly fine but when I go to run `npm install` I get a bunch of warnings, not sure if this is normal.

`Kyles-MacBook-Pro:Resume kyleweise$ git clone https://github.com/salomonelli/best-resume-ever`
`Cloning into 'best-resume-ever'...`
`remote: Counting objects: 2559, done.`
`remote: Compressing objects: 100% (30/30), done.`
`remote: Total 2559 (delta 21), reused 22 (delta 9), pack-reused 2520`
`Receiving objects: 100% (2559/2559), 23.91 MiB | 7.62 MiB/s, done.`
`Resolving deltas: 100% (1351/1351), done.`
`Kyles-MacBook-Pro:Resume kyleweise$ npm install`
`npm WARN saveError ENOENT: no such file or directory, open` `'/Users/kyleweise/Desktop/Resume/package.json'`
`npm notice created a lockfile as package-lock.json. You should commit this file.`
`npm WARN enoent ENOENT: no such file or directory, open` `'/Users/kyleweise/Desktop/Resume/package.json'`
`npm WARN Resume No description`
`npm WARN Resume No repository field.`
`npm WARN Resume No README data`
`npm WARN Resume No license field. `
`up to date in 0.417s`

Assuming it was normal, i went ahead and changed the `person.js` file accordingly, and tried to run `npm run dev` and I get these errors.

`Kyles-MacBook-Pro:Resume kyleweise$ npm run dev`
`npm ERR! path /Users/kyleweise/Desktop/Resume/package.json`
`npm ERR! code ENOENT`
`npm ERR! errno -2`
`npm ERR! syscall open`
`npm ERR! enoent ENOENT: no such file or directory, open` `'/Users/kyleweise/Desktop/Resume/package.json'`
`npm ERR! enoent This is related to npm not being able to find a file.`
`npm ERR! enoent `

`npm ERR! A complete log of this run can be found in:`
`npm ERR!     /Users/kyleweise/.npm/_logs/2017-09-21T18_17_07_266Z-debug.log`

I'm pretty new to node and npm, so any help with this would be appreciated!

**Comment by mbndr** [comment]
I think you forgot to cd into the repo
```bash
git clone https://github.com/salomonelli/best-resume-ever
cd best-resume-ever # cd into repository
npm install
```

**Comment by kundan333** [comment]
what should i do i got this problem while running `npm run dev`

![image](https://user-images.githubusercontent.com/14930157/30715615-4e642758-9eaa-11e7-964a-d684e929c8b5.png)

**Comment by kyleweise** [comment]
ahhhh now I feel dumb 😐 . thanks @mbndr !

**Comment by mbndr** [comment]
You're welcome :)
@kundan333 please open a new issue
