### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by unix-root** [salomonelli/best-resume-ever#66]
getting EINTEGRITY error during npm install

### Case
<Installation bug>

## Issue
integrity checksum failure

## Info
- Operating System: macOS Sierra
- Node-Version: v8.5.0
- npm-version: 5.3.0

## Reproduce
git clone https://github.com/salomonelli/best-resume-ever.git
cd best-resume-ever
npm init
npm install
![screen shot 2017-09-22 at 9 57 05 am](https://user-images.githubusercontent.com/24273309/30729332-748a7a04-9f7c-11e7-8ec1-9a96195cc04e.png)
l

**Comment by mbndr** [comment]
Try it without `npm init`. This command will create a new `package.json`.

**Comment by unix-root** [comment]
Sorry, my bad. It was a npm issue. I rushed here without checking the errors.
