### ISSUE TITLE
Change "name" and "position" positions in material-blue so that they are presented clearly with any person.jpg color

### ISSUE THREAD

**Issue by czonios** [salomonelli/best-resume-ever#7]
![material-blue](https://user-images.githubusercontent.com/16341063/30247598-cf0afa90-9620-11e7-93ec-810aaf3c0b0b.jpg)
As you can see from this image the black text doesn't work over every image the same. Consider changing it's position or adding a semi-transparent black background with white letters instead of black.

I can take this issue and try to fix it if you want to assign it to me.

Thank you for a great resume building tool!

**Comment by salomonelli** [comment]
Hello @czonios,

the text color will never fit to every possible image. This is not only a problem with the material-blue-template, but also other templates.

Each user should change the text color, so it fits their image.
