### ISSUE TITLE
Does not preview or export entire resume

### ISSUE THREAD

**Issue by mgrigajtis** [salomonelli/best-resume-ever#70]
### Case
- BUG

## Issue
When previewing or exporting to PDF, only about 3/4ths of the resume is shown.

## Info
- Operating System: Windows
- Node-Version: v8.5.0

## Reproduce
npm run dev
npm run export

**Comment by mbndr** [comment]
Is it cut off after 3/4 of the page and only white? A Screenshot would be great.

**Comment by mgrigajtis** [comment]
The export to PDF looks the same.  All templates do this.

![image](https://user-images.githubusercontent.com/238225/30748550-a5b43f64-9f7e-11e7-8242-257eebafe4be.png)

**Comment by mbndr** [comment]
The problem is that the page size is limited to DIN-A4 format (see https://github.com/salomonelli/best-resume-ever/blob/master/src/pages/resume.vue#L50).
I don't know how @salomonelli wants to handle this?

**Comment by mgrigajtis** [comment]
Makes sense, maybe add the ability to handle multiple pages?

**Comment by KingJavaJava** [comment]
Hello i'm getting this error, any idea what I need to do?

module.js:529
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rexorioko/Documents/best-resume-ever/build/check-versions.js:2:14)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! best-resume-ever@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the best-resume-ever@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rexorioko/.npm/_logs/2017-10-02T18_26_09_626Z-debug.log

**Comment by mbndr** [comment]
Please open a new issue for your error.

**Comment by ineeve** [comment]
Hi! I have managed to replicate this bug very easily. By adding more than 2 skills, the third one will already not be displayed.

**Comment by ineeve** [comment]
I experiment setting page height to auto on resume.vue and it seems to work. On exporting it creates a pdf with 2 pages already. I will make a pull request for this small change.

**Comment by salomonelli** [comment]
I have updated the exporting process so that border shadows are displayed properly. If the resume is too long it will be still cut off. Generally CVs are meant to be one-pagers. The designs were made with that intention. 

If you need multiple pages then maybe a PR with a new template suiting multiple pages would be practical. But apart from the new template the exporting must be adjusted as well.
