### ISSUE TITLE
npm run dev 'relative module was not found'

### ISSUE THREAD

**Issue by unix-root** [salomonelli/best-resume-ever#71]
### Case
Help Question

## Issue
I got one error while executing dev: "* ./src/main.js in multi ./build/dev-client ./src/main.js"

## Info
- Operating System: OSX
- Node-Version: 8.5.0
- npm-Version: 5.4.2

## Reproduce
After installing all dependencies -> npm run dev gave this error.
![screen shot 2017-09-23 at 3 29 26 pm](https://user-images.githubusercontent.com/24273309/30772227-fd57279e-a074-11e7-96c1-52276eefa38c.png)

**Comment by pubkey** [comment]
Can anyone reproduce this on OSX?
@unix-root at which folder did you run `npm run dev` ?

**Comment by unix-root** [comment]
Sorry, it was all my fault, my node_modules folder had many different packages which were not needed. I tried reinstalling, It works great.
