### ISSUE TITLE
Making angular varient

### ISSUE THREAD

**Issue by sagarkaurav** [salomonelli/best-resume-ever#77]
Can i make angular variant for this project's using the project styling and resources.

**Comment by pubkey** [comment]
What would be the benefit?

**Comment by mbndr** [comment]
I guess with the MIT license it shouldn't be a problem.
https://github.com/salomonelli/best-resume-ever/blob/master/LICENCE.md

**Comment by sagarkaurav** [comment]
@mbndr yes i will use MIT license.

**Comment by sagarkaurav** [comment]
I am porting code in angular just for learning purpose

**Comment by pubkey** [comment]
I think this is resolved. @sagarkaurav just include the license and everything is fine.
