### ISSUE TITLE
Templates for Right to Left

### ISSUE THREAD

**Issue by msarsha** [salomonelli/best-resume-ever#8]

**Comment by salomonelli** [comment]
What does RTL mean?

**Comment by msarsha** [comment]
Right to Left

**Comment by eladcandroid** [comment]
To support languages like Hebrew, Arabic etc..

**Comment by salomonelli** [comment]
I see ... A PR for template supporting rtl is welcome and highly appreciated!

**Comment by lielfr** [comment]
Hi! I'm planning to work on it. Should it be as new templates or included within the existing ones?

**Comment by salomonelli** [comment]
Hi @lielfr, please just create new templates.

**Comment by yoavmmn** [comment]
@salomonelli I'm planning to work on this as well. It'd be great if you'd assigned it to me.

**Comment by yoavmmn** [comment]
I've added the first RTL template based on side-bar template. you can check it out at #83.
