### ISSUE TITLE
npm run export    ERROR:  node_modules\electron\index.js:9 

### ISSUE THREAD

**Issue by eMe-404** [salomonelli/best-resume-ever#85]
### Case

BUG

## Issue

every time use npm run export will get this:
> Listening at http://localhost:8080

Connected to server ...
Exporting ...
(node:13204) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error: Command failed: electroshot localhost:8080/#/resume/left-right 2481x3508 --pdf-margin none --format pdf --out E:\best-resume-ever-master\pdf --filename "left-right.pdf" --pdf-background && electroshot localhost:8080/#/resume/material-blue 2481x3508 --pdf-margin none --format pdf --out E:\best-resume-ever-master\pdf --filename "material-blue.pdf" --pdf-background && electroshot localhost:8080/#/resume/material-dark 2481x3508 --pdf-margin none --format pdf --out E:\best-resume-ever-master\pdf --filename "material-dark.pdf" --pdf-background && electroshot localhost:8080/#/resume/oblique 2481x3508 --pdf-margin none --format pdf --out E:\best-resume-ever-master\pdf --filename "oblique.pdf" --pdf-background && electroshot localhost:8080/#/resume/side-bar 2481x3508 --pdf-margin none --format pdf --out E:\best-resume-ever-master\pdf --filename "side-bar.pdf" --pdf-background
E:\best-resume-ever-master\node_modules\electron\index.js:9
  throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
  ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> (E:\best-resume-ever-master\node_modules\electron\index.js:9:9)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\best-resume-ever-master\node_modules\electroshot\bin\electroshot.js:8:16)
    at Module._compile (module.js:624:30)

(node:13204) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Process finished with exit code 0

but the npm run dev working 
## Info
- Operating System:  Win 10
- Node-Version:  v8.6.0

## Reproduce

first step: I use  npm install and edit the person.js
second step: use npm run dev  (it is working)
third step: use npm run export then it shows that ERROR

**Comment by eMe-404** [comment]
delete node_modules/electron and try installing again 
then problem fixed ...

**Comment by youngjuning** [comment]
![2017-11-18_152023](https://user-images.githubusercontent.com/13204332/32978206-6232ad94-cc78-11e7-921a-be11ca46aa51.png)
