### ISSUE TITLE
npm install 

### ISSUE THREAD

**Issue by xjtuztSap** [salomonelli/best-resume-ever#98]
## Info
- Operating System: 
- Node-Version: 

## Reproduce

Hello, when I run 'npm install', 'Error: socket hang up' is reported.
Details is as below, thx for reply:

> electron@1.6.15 postinstall /Users/Aaron/Desktop/best-resume-ever/node_modules/electron
> node install.js

/Users/Aaron/Desktop/best-resume-ever/node_modules/electron/install.js:48
  throw err
  ^

Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1094:19)
    at TLSSocket.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
best-resume-ever@1.0.0 /Users/Aaron/Desktop/best-resume-ever
└── (empty)

npm WARN best-resume-ever@1.0.0 No repository field.
npm WARN best-resume-ever@1.0.0 No license field.
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! electron@1.6.15 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.6.15 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Aaron/Desktop/best-resume-ever/npm-debug.log
npm ERR! code 1

**Comment by pubkey** [comment]
Which node-version?

**Comment by xjtuztSap** [comment]
I have tried node with version 6.9.1/8.1.3/8.7.0, all get the same error.
![image](https://user-images.githubusercontent.com/8231784/31720198-7b883c9c-b3db-11e7-8b26-396aa3baea37.png

)

**Comment by pubkey** [comment]
Can you create an empty folder and do `npm i electron`?

**Comment by xjtuztSap** [comment]
Done ! 
I reset the ELECTRON_MIRROR as below:
ELECTRON_MIRROR=http://npm.taobao.org/mirrors/electron/ npm install electron --save-dev

Thx again.
